version: "3"

services:
  client:
    image: nik/future-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env

    working_dir: /app

    ports:
      - 8000:8000
